Ikaros/Models/Node.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Genxyz.Models
{
    public class Node
    {
        public int NodeID { get; set; }
        public int InstanceID { get; set; }

        public string Name { get; set; }
        public string Comments { get; set; }

        public float xPos { get; set; }
        public float yPos { get; set; }
        public float zPos { get; set; }

        public List<int> LinksID { get; set; } 
        public List<Link> Links { get; set; }

        public bool Active { get; set; }

        public DateTime CreatedOn { get; set; }
        public DateTime LastModified { get; set; }

        public Node()
        {

        }

        public Node(CreateNode n)
        {
            Name = n.Name;
            Comments = n.Comments;
            xPos = n.xPos;
            yPos = n.yPos;
            zPos = n.zPos;
            InstanceID = n.InstanceID;
            Active = true;

            CreatedOn = DateTime.Now;
            LastModified = DateTime.Now;
        }

        public void EditNode(EditNode n)
        {
            Name = n.Name;
            Comments = n.Comments;
            xPos = n.xPos;
            yPos = n.yPos;
            zPos = n.zPos;

            LastModified = DateTime.Now;
        }

        public void DeleteNode()
        {
            if (Active)
            {
                Active = false;
                LastModified = DateTime.Now;
            }
        }

        public void ActivateNode()
        {
            if (!Active)
            {
                Active = true;
                LastModified = DateTime.Now;
            }
        }
    }

    public class CreateNode
    {
        public int? ParentNodeID { get; set; }
        public int? SiblingNodeID { get; set; }

        [Required]
        public string Name { get; set; }
        public string Comments { get; set; }

        [Required]
        public float xPos { get; set; }
        [Required]
        public float yPos { get; set; }
        [Required]
        public float zPos { get; set; }

        [Required]
        public virtual int LayerID { get; set; }

        public int InstanceID { get; set; }
    }

    public class EditNode
    {
        public int NodeID { get; set; }
        public int InstanceID { get; set; }

        [Required]
        [Display(Name="Title", Prompt ="Title")]
        public string Name { get; set; }
        [Display(Name="Description", Prompt ="Description")]
        public string Comments { get; set; }

        [Required]
        [Display(Name="X")]
        public float xPos { get; set; }
        [Required]
        [Display(Name = "Y")]
        public float yPos { get; set; }
        [Required]
        [Display(Name = "Z")]
        public float zPos { get; set; }
    }
}

Ikaros/Models/NodeType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Genxyz.Models
{
    public class NodeType
    {
        public int NodeTypeID { get; set; }

        [Required]
        public string Name { get; set; }
        [Required]
        public string Color { get; set; }
        public int Importance { get; set; }

        [Required]
        public int InstanceID { get; set; }
        public Instance Instance { get; set; }
    }
}

Ikaros/Controllers/NodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Genxyz.Models;

namespace Genxyz.Controllers
{
    public class NodesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();



        public NodesController()
        {

        }
        //admin features... gotta add protection later. We'll get there.
        public ActionResult CleanNodes()
        {
            var LayerLinks = db.LayerLinks.Where(x => x.Active).ToList();
            var Nodes = db.Nodes.Where(x => x.Active).ToList();
            List<Node> NodesToClean = new List<Node>();
            foreach (var n in Nodes)
            {
                if (!LayerLinks.Any(x=>x.NodeID == n.NodeID))
                {
                    NodesToClean.Add(n);
                }
            }

            foreach (var n in NodesToClean)
            {
                //first check to see if instance has any layers to begin with.
                var Layer = db.Layers.DefaultIfEmpty(null).FirstOrDefault(x => x.InstanceID == n.InstanceID);
                if (Layer == null)
                {
                    Layer = new Layer(new CreateLayer
                    {
                        InstanceID = n.InstanceID,
                        Name = "Default"
                    });
                    db.Layers.Add(Layer);
                    db.SaveChanges();
                }
                db.LayerLinks.Add(
                new LayerLink(
                    new CreateLayerLink
                    {
                        NodeID = n.NodeID,
                        LayerID = Layer.LayerID
                    }));
            }
            db.SaveChanges();
            return RedirectToAction("","Home");
        }

        public ActionResult DeleteInactive()
        {
            //delete all inactive layerlinks, layers and nodes.
            var layerLinks = db.LayerLinks.RemoveRange(db.LayerLinks.Where(x => x.Active == false));
            var Nodes = db.Nodes.RemoveRange(db.Nodes.Where(x => x.Active == false));
            var Layers = db.Layers.RemoveRange(db.Layers.Where(x => x.Active == false));
            db.SaveChanges();
            return RedirectToAction("", "Home");
        }

        //create a layer
        [HttpPost]
        [FindInInstance]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePath([Bind]CreateLayer c, int InstanceID)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { error = Generic.GetValidationErrors(ModelState) });
            }
            var layer = new Layer(c);
            db.Layers.Add(layer);
            db.SaveChanges();
            //crate layer links, if appropriate.
            List<LayerLink> LayerLinks = new List<LayerLink>();
            if (c.Nodes != null)
            {
                foreach (var x in c.Nodes)
                {
                    var node = db.Nodes.DefaultIfEmpty(null).FirstOrDefault(y => y.NodeID == x && y.InstanceID == InstanceID);
                    if (node == null)
                    {
                        continue;
                    }
                    var thisLink = new LayerLink(new CreateLayerLink { LayerID = layer.LayerID, NodeID = x });
                    LayerLinks.Add(thisLink);
                }
            db.LayerLinks.AddRange(LayerLinks);
            db.SaveChanges();
            }

            var jsonLinks = new List<JsonLayerLink>();
            foreach (var l in LayerLinks)
            {
                jsonLinks.Add(new JsonLayerLink(l));
            }
            return Json(new
            {
                layer = new JsonLayer(layer),
                layerLinks = jsonLinks
            });
        }

/*        //create the nodes!
        public ActionResult CreateNode(int InstanceID, int parentID = -1, int siblingID = -1, int posX = 0, int posY = 0)
        {
            CreateNode node = new CreateNode{ParentNodeID = parentID, SiblingNodeID = siblingID, xPos = posX, yPos = posY, InstanceID = InstanceID};
            return PartialView("_CreateNode", node);
        }*/

        [ValidateAntiForgeryToken]
        [HttpPost]
        [FindInInstance]
        public ActionResult CreateNode([Bind] CreateNode Node, int InstanceID)
        {
            if (ModelState.IsValid)
            {
                //make sure the layer exists in this instance.
                var Layer = db.Layers.DefaultIfEmpty(null).FirstOrDefault(x => x.InstanceID == Node.InstanceID && x.LayerID == Node.LayerID);
                if (Layer == null)
                {
                    ModelState.AddModelError("Layer", "Unable to find Layer.");
                    return Json(new { error = Generic.GetValidationErrors(ModelState) });
                }
                //

                Node node = new Node(Node);
                db.Nodes.Add(node);
                node.Links = new List<Link>();
                db.SaveChanges();
                Link Link = null;
                //create a link if needed.
                if (Node.ParentNodeID != null)
                {
                    CreateLink l = new CreateLink
                    {
                        OriginID = (int) Node.ParentNodeID,
                        TargetID = node.NodeID,
                        Type = "Parent"
                    };
                    Link = new Link(l);
                    db.Links.Add(Link);
                    db.SaveChanges();
                }


                if (Node.SiblingNodeID != null)
                {
                    CreateLink l = new CreateLink
                    {
                        OriginID = (int)Node.ParentNodeID,
                        TargetID = node.NodeID,
                        Type = "Sibling"
                    };
                    Link = new Link(l);
                    db.Links.Add(Link);
                    //node.Links.Add(l);
                    db.SaveChanges();
                }

                //link to the layer.
                var layerLink = new LayerLink(new CreateLayerLink { NodeID = node.NodeID, LayerID = Node.LayerID });
                db.LayerLinks.Add(layerLink);
                db.SaveChanges();
                return Json(new { node= node, layerlink = new JsonLayerLink(layerLink), link = Link});
            }
            
            return Json (new { error = Generic.GetValidationErrors(ModelState)});
        }

        [FindInInstance]
        public ActionResult DeleteNode(int InstanceID, int nodeId){
            return PartialView("_DeleteNode", db.Nodes.Where(x=>x.InstanceID == InstanceID).FirstOrDefault(x=>x.NodeID == nodeId));
        }

        //remove links.
        [FindInInstance]
        [HttpPost]
        public ActionResult RemoveLinks(int InstanceID, int nodeId)
        {
            RemoveLinks(nodeId);

            return Json(new { success = "Success!" });
        }

        [FindInInstance]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveLink(int InstanceID, int LinkID)
        {
            var link = db.Links.DefaultIfEmpty(null).FirstOrDefault(x => x.LinkID == LinkID);
            if (link == null)
            {
                ModelState.AddModelError("", "Invalid link.");
                return Json(new { error = Generic.GetValidationErrors(ModelState) });
            }
            //confirm in instance.
            var node = db.Nodes.DefaultIfEmpty(null).FirstOrDefault(x => x.NodeID == link.OriginID && x.InstanceID == InstanceID);
            if (node == null)
            {
                ModelState.AddModelError("", "Invalid link.");
                return Json(new { error = Generic.GetValidationErrors(ModelState) });
            }
            link.Active = false;
            db.SaveChanges();
            return Json(new { success = "Success!" });
        }

        //delete node.
        [HttpPost]
        [ActionName("DeleteNodes")]
        [FindInInstance]
        public ActionResult DeleteNodePost(int[] NodeIDs, int InstanceID)   {
            foreach (int i in NodeIDs)
            {
                var node = db.Nodes.Where(x => x.InstanceID == InstanceID).FirstOrDefault(x => x.NodeID == i);
                if (node == null)
                {
                    ModelState.AddModelError("", "Node "+i+" not found");
                } else
                {
                    RemoveLinks(i);
                    RemoveLayerLinks(i);
                    node.DeleteNode();
                }
            }
            if (!ModelState.IsValid)
            {
                return Json(new { error = Generic.GetValidationErrors(ModelState) });
            }
            db.SaveChanges();
            //now clear out all the links.
            return Json(new { success = "Success!" });
        }

        //remove a link between a node and a layer. used inside controller, not reachable from outside.
        //probably going to move to node model instead.
        private void RemoveLayerLinks(int nodeID)
        {
            List<LayerLink> LinksToRemove = db.LayerLinks.Where(x => x.NodeID == nodeID).ToList();
            LinksToRemove.ForEach(x => x.RemoveLayerLink());
        }

        //Remove links.
        public bool RemoveLinks(int nodeId)
        {
            List<Link> LinksToRemove = db.Links.Where(x => x.OriginID == nodeId || x.TargetID == nodeId).ToList();
            foreach (var l in LinksToRemove)
            {
                l.RemoveLink();
            }
            db.SaveChanges();

            return true;
        }

        [FindInInstance]
        public ActionResult EditNode(int nodeId, int InstanceID)
        {
            return PartialView("_EditNode", db.Nodes.Where(x=>InstanceID == x.InstanceID).FirstOrDefault(x=>x.NodeID == nodeId));
        }

        //Edit a node.
        [HttpPost]
        [FindInInstance]

Ikaros/Views/Nodes/_ChildLinks.cshtml
<span class="genxyz-detailsSubMenuTitle">Children</span>
<div class="genxyz-detailsSubMenuContent">
    Links go here!<br />
    So many links!
</div>

Ikaros/Views/Nodes/_CreateLayer.cshtml
@model Genxyz.Models.CreateLayer

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(x => x.InstanceID)
    @Html.Raw("New Layer Name:<br />")
    @Html.TextBoxFor(x => x.Name, new { @id ="newLayerName", @class = "click-on-enter ignore-other-inputs", data_target = "/Nodes/CreateLayer", data_click = "createLayerConfirm"})
    <span id="createLayerConfirm" class="btn btn-success" data-target="/Nodes/CreateLayer"><span class="fa fa-floppy-o"></span></span>
}

Ikaros/Views/Nodes/_CreateNode.cshtml
@model Genxyz.Models.CreateNode

<div id="genxyz-input-container" class="genxyz-input" data-node="true">
    @using (Html.BeginForm("CreateNode", "Nodes"))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(x => x.ParentNodeID)
        @Html.HiddenFor(x => x.SiblingNodeID)
        @Html.HiddenFor(x => x.xPos)
        @Html.HiddenFor(x => x.yPos)
        @Html.HiddenFor(x => x.zPos)
        @Html.HiddenFor(x => x.InstanceID)
        @Html.HiddenFor(x => x.LayerID)
        @Html.HiddenFor(x => x.Comments)

        @Html.TextAreaFor(x => x.Name, new { @class = "textarea-autosize ignore-other-inputs node-input", @id="genxyz-createNodeName"})
        <span class="submit-form-button" hidden></span>
    }

    @*some meta data in here.*@
    @* Used to watch to determine how to push the next step. Haven't decided how to use it just yet. *@
    @Html.Hidden("PushDirShift", null, new { @class = "pushDirData" })
    @Html.Hidden("PushDirCtrl", null, new { @class = "pushDirData" })
    @Html.Hidden("PushDirPositiveGrow", null, new { @class = "pushDirData" })
    @Html.Hidden("PushDirCount", null, new { @class = "pushDirData" })
</div>

Ikaros/Views/Nodes/_DeleteNode.cshtml
@model Genxyz.Models.Node

<div id="genxyz-deleteMenu" hidden>

    <span class="errors text-warning">Are you sure you want to delete this node?</span>

    @Html.HiddenFor(model => model.NodeID)
    @Html.HiddenFor(model => model.InstanceID)

    <div>
        <input type="button" value="Delete" class="btn btn-default" id="PostDeleteNode" />
    </div>
</div>

Ikaros/Views/Nodes/_Details.cshtml
<div id="genxyz-detailsContainer">
    <div class="genxyz-detailsSubMenu" id="genxyz-editMenu">@Html.Partial("~/Views/Nodes/_EditNode.cshtml")</div>
    <div class="genxyz-detailsSubMenu" id="genxyz-parentLinksMenu">@Html.Partial("~/Views/Nodes/_ParentLinks.cshtml")</div>
    <div class="genxyz-detailsSubMenu" id="genxyz-childLinksMenu">@Html.Partial("~/Views/Nodes/_ChildLinks.cshtml")</div>
    <div class="genxyz-detailsSubMenu" id="genxyz-symbolicLinksMenu">@Html.Partial("~/Views/Nodes/_SymbolicLinks.cshtml")</div>
    <div class="genxyz-detailsSubMenu" id="genxyz-pathsMenu">@Html.Partial("~/Views/Nodes/_Paths.cshtml")</div>
</div>

Ikaros/Views/Nodes/_EditLayer.cshtml
@model Genxyz.Models.EditLayer

@using (Html.BeginForm())
{
    <span class="paddedContainer">
        @Html.AntiForgeryToken()

        @Html.HiddenFor(x => x.InstanceID)
        @Html.HiddenFor(x => x.LayerID)

        <span class="horizontal-container full-width">
            <span class="genxyz-menu-input-label">Edit Layer:</span>
            @Html.TextBoxFor(x => x.Name, new { @class = "ignore-other-inputs genxyz-menu-input" })
        </span><br />
        <span class="horizontal-container full-width">
            <span id="edit-Layer" class="btn btn-success submit-form-button float-right" data-target="/Nodes/EditLayer"><span class="fa fa-floppy-o"></span></span>
            <span id="delete-Layer" class="btn btn-danger float-right"><span class="fa fa-trash"></span></span>
        </span><br /><br />
        <span class="horizontal-container full-width">
            <span id="delete-Container" style="display:none;" class="float-right">
                <span>Confirm delete: <span id="delete-layer-confirm" class="btn btn-danger" data-target="/Nodes/DeleteLayer"><span class="fa fa-trash"></span></span></span>
            </span>
        </span>
    </span>
}

Ikaros/Views/Nodes/_EditNode.cshtml
@model Genxyz.Models.EditNode

@using (Html.BeginForm("UpdateNode", "Nodes"))
{
    @Html.HiddenFor(model => model.InstanceID)
    @Html.HiddenFor(model => model.NodeID)
    <span class="genxyz-detailsSubMenuTitleBar"><span class="genxyz-detailsSubMenuTitle">Node <span class="NodeID"></span></span></span>
    <div class="genxyz-detailsSubMenuContent">
        <table class="thinTable">
            <tr>
                <th>xPos:</th>
                <th>yPos:</th>
                <th>zPos:</th>
            </tr>
            <tr>
                <td>
                    @Html.TextBoxFor(x => x.xPos)
                </td>
                <td>
                    @Html.TextBoxFor(x => x.yPos)
                </td>
                <td>
                    @Html.TextBoxFor(x => x.zPos)
                </td>
            </tr>
        </table>
        <span class="horizontal-container">
            @Html.TextBoxFor(x => x.Name, new { @class = "ignore-other-inputs transparent-textarea genxyz-menu-input full-width", @placeholder = "Title..." })
        </span>
        <span class="horizontal-container">
            @Html.TextAreaFor(x => x.Comments, new { @class = "ignore-other-inputs transparent-textarea genxyz-menu-input full-width", @placeholder = "Description...", @rows="4" })
        </span>
        <span class="horizontal-container">
            @GenericHelper.Button("<span class='fa fa-save'></span>", "genxyz-editNode-save", "success", "float-right")
        </span>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ikaros/Views/Nodes/_ParentLinks.cshtml
<span class="genxyz-detailsSubMenuTitle">Parents</span>
<div class="genxyz-detailsSubMenuContent">
    Links go here!<br />
    So many links!
</div>

Ikaros/Views/Nodes/_Paths.cshtml
<span class="genxyz-detailsSubMenuTitle redTitle">Paths</span>
<div class="genxyz-detailsSubMenuContent">
    All the paths!
    <br />P
    <br />ath
    <br />s!
</div>

Ikaros/Views/Nodes/_RightClickMenu.cshtml
@* when right clicking without any node selected, and without any target. *@
<div id="right-click-menu-noTarget" class="right-click-menu" hidden>
    <div class="listItem">No option to show... for now.</div>
</div>

@* when right clicking anywhere, with nodes selected. *@
<div id="right-click-menu-selected" class="right-click-menu" hidden>
    <div class="listItem" id="deleteNodeMenu">Delete Nodes</div>
    <div class="listItem" id="deleteNodeConfirm" hidden>Confirm Delete<span class="align-right"><span class="fa fa-trash"></span></span></div>
    <div class="listItem" id="addNodesToPath">Add to Path</div>
    <div class="listItem" id="createPathFromNodes">Create Path from Nodes</div>
    <div class="listItem" id="createPathFromNodesChildren">Create Path from Nodes + Children</div>
</div>
@* when right clicking on a node. *@
<div id="right-click-menu-selected-target" class="right-click-menu" hidden>
</div>

Ikaros/Views/Nodes/_SymbolicLinks.cshtml
<span class="genxyz-detailsSubMenuTitle redTitle">Symbolic Links</span>
<div class="genxyz-detailsSubMenuContent">
    More links go here!<br />
    So many links!
</div>