Ikaros/Models/Instance.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Genxyz.Models
{
    public class Instance
    {
        public virtual int InstanceID { get; set; }

        public virtual string Name { get; set; }
        public virtual bool Active { get; set; }

        public string Creator { get; set; }
        public DateTime CreationDate { get; set; }

        public List<Member> Members { get; set; }
        public List<NodeType> NodeTypes { get; set; }

        public int InstanceConfigurationID { get; set; }
        public InstanceConfiguration InstanceConfiguration { get; set; }

        public virtual List<Layer> Layers { get; set; }
    }

    public class InstanceCreate
    {
        [Required]
        [MinLength(5, ErrorMessage = "Name needs to be at least 5 characters.")]
        public virtual string Name { get; set; }
    }

    public class InstanceIndex
    {
        public virtual int InstanceID { get; set; }

        public virtual string Name { get; set; }

        [Display(Name = "Created by")]
        public virtual string CreatorName { get; set; }

        [Display(Name = "Created on")]
        public virtual DateTime CreationDate { get; set; }

        public virtual string Creator { get; set; }

        public InstanceIndex(Instance i)
        {
            InstanceID = i.InstanceID;

            Name = i.Name;
            CreationDate = i.CreationDate;
            Creator = i.Creator;
            CreatorName = Generic.GetUserDisplayName("", i.Creator);
        }
    }

    public class InstanceEdit
    {
        [Required]
        [MinLength(5, ErrorMessage = "Name needs to be at least 5 characters.")]
        public virtual string Name { get; set; }

        //more stuff later?
    }

}

Ikaros/Controllers/InstancesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Genxyz.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Genxyz.Controllers
{
    [Authorize]
    public class InstancesController : Controller
    {
        DateTime Time
        {
            get
            {
                if (Session["TimeStamp"] == null)
                {
                    Session["TimeStamp"] = DateTime.MinValue;
                }
                return (DateTime)Session["TimeStamp"];
            }
            set
            {

            }
        }

        DateTime TempTime
        {
            get
            {
                if (Session["TempTimeStamp"] == null)
                {
                    Session["TempTimeStamp"] = DateTime.MinValue;
                }
                return (DateTime)Session["TempTimeStamp"];
            }
            set
            {

            }
        }

        private ApplicationDbContext db = new ApplicationDbContext();
        private UserManager<ApplicationUser> manager = new UserManager<ApplicationUser>(
            new UserStore<ApplicationUser>(
                new ApplicationDbContext()));

        public ActionResult GetInstances()
        {
            var myUsername = Generic.GetUserName();
            var instances = db.Instances.Where(x => x.Active && x.Members.Any(y => y.UserName == myUsername) == true).ToList();
            List<InstanceIndex> instancesIndices = new List<InstanceIndex>();
            foreach (var i in instances)
            {
                instancesIndices.Add(new InstanceIndex(i));
            }
            return PartialView("_GetInstances", instancesIndices);
        }

        public ActionResult InboundInvites()
        {
            var myUserName = Generic.GetUserName();
            var invites = db.Invites.Where(x => x.Accepted == null && x.Active == true && x.Recipient == myUserName);
            if (invites.Count() > 0)
            {
                var inviteList = new List<InboundInvites>();
                foreach (var i in invites)
                {
                    inviteList.Add(new InboundInvites(i));
                }
                return PartialView("_InboundInvites", inviteList);
            }
            return null;
        }


        //get members of an instance.
        [FindInInstance]
        public ActionResult InstanceMembers(int InstanceID)
        {
            var members = db.Members.Where(x => x.InstanceID == InstanceID);
            var memberList = new List<MemberList>();

            foreach (var m in members)
            {
                memberList.Add(new MemberList(m));
            }

            var invitees = db.Invites.Where(x => x.InstanceID == InstanceID && x.Accepted == null && x.Active).ToList();

            foreach (var i in invitees)
            {
                memberList.Add(new MemberList(i));
            }

            ViewBag.InstanceID = InstanceID;

            return PartialView("_InstanceMembers", memberList);
        }

        // GET: Instances
        public ActionResult Index()
        {
            return View(db.Instances.Where(x=>x.Active).ToList());
        }
        
        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost, ActionName("CreateJSON")]
        [ValidateAntiForgeryToken]
        public ActionResult CreateInstance([Bind(Include ="Name")] InstanceCreate instance)
        {
            if (ModelState.IsValid)
            {
                var config = new InstanceConfiguration { DisplayName = instance.Name, BackgroundColor = "rgba(0,0,0,1)" };
                db.InstanceConfigurations.Add(config);
                db.SaveChanges();
                var usr = Generic.GetUserName();
                var inst = new Instance
                {
                    Name = instance.Name,
                    Creator = usr,
                    CreationDate = DateTime.Now,
                    Members = new List<Member>(),
                    Active = true,
                    InstanceConfigurationID = config.InstanceConfigurationID
                };
                db.Instances.Add(inst);
                db.SaveChanges();
                var layer = new Layer ( new CreateLayer { InstanceID = inst.InstanceID, Name = "Default" });
                var mem = new Member { UserName = usr, InstanceID = inst.InstanceID };
                db.Layers.Add(layer);
                db.Members.Add(mem);
                db.SaveChanges();
                return Json(new { refresh = true });
            }
            return Json(new { error = Generic.GetValidationErrors(ModelState) });
        }


        public ActionResult DeleteInstance()
        {
            return PartialView("_Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [InstanceOwner]
        public ActionResult DeleteJSON(int InstanceID)
        { 
            var instance = db.Instances.FirstOrDefault(x => x.Active && x.InstanceID == InstanceID);
            if (instance == null)
            {
                ModelState.AddModelError("", "Unable to find instance.");
            }
            
            if (!ModelState.IsValid)
            {
                return Json(new { error = Generic.GetValidationErrors(ModelState) });
            }

            //now delete.
            instance.Active = false;
            db.SaveChanges();

            return Json(new { refresh = true });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [InstanceOwner]
        public ActionResult EditInstance([Bind(Prefix ="item")] InstanceEdit edit, int InstanceID)
        {
            var instance = db.Instances.FirstOrDefault(x => x.Active && x.InstanceID == InstanceID);
            if (instance == null)
            {
                ModelState.AddModelError("", "Unable to find instance.");
            }

            if (!ModelState.IsValid)
            {
                return Json(new { error = Generic.GetValidationErrors(ModelState) });
            }

            instance.Name = edit.Name;
            db.SaveChanges();

            return Json(new { success = true });
        }

        #region Invites.
        [FindInInstance]
        public ActionResult CreateInvite(int InstanceID)
        {
            return PartialView("_CreateInvite", new CreateInvite { InstanceID = InstanceID });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [FindInInstance]
        public ActionResult SendInvite([Bind(Include ="InstanceID,Recipient")] CreateInvite invite, int InstanceID)
        {
            if (ModelState.IsValid)
            {
                if (manager.FindByEmail(invite.Recipient) == null)
                {
                    ModelState.AddModelError("Recipient", "Not a valid user");
                }

                if (invite.Recipient == Generic.GetUserName())
                {
                    ModelState.AddModelError("Recipient", "Cannot invite yourself");
                }

                //now see if another invite already exists for this instance and user and is active.
                var existing = db.Invites.Any(x => x.Accepted == null && x.Active && x.Recipient == invite.Recipient && x.InstanceID == invite.InstanceID);
                if (existing)
                {
                    ModelState.AddModelError("Recipient", "User has a pending invite.");
                }

                //and of course, confirm that user doesn't already exist in the instance.
                existing = db.Members.Any(x => x.InstanceID == invite.InstanceID && x.UserName == invite.Recipient);
                if (existing)
                {
                    ModelState.AddModelError("Recipient", "User is already a member.");
                }

                if (ModelState.IsValid)
                {
                    var newInvite = new Invite(invite);
                    db.Invites.Add(newInvite);
                    db.SaveChanges();
                    return Json(new { refresh = true });
                }
            }
            return Json(new { error = Generic.GetValidationErrors(ModelState) });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ReplyInvite(int InviteID, bool Accept)
        {
            var thisInv = db.Invites.Find(InviteID);
            if (thisInv == null || thisInv.Active == false)
            {
                ModelState.AddModelError("Recipient", "Could not find invite.");
            } else if (thisInv.Recipient != Generic.GetUserName())
            {
                ModelState.AddModelError("Recipient", "Could not find invite.");
            } else
            {
                var inst = db.Instances.Include("Members").FirstOrDefault(x=> x.Active && x.InstanceID == thisInv.InstanceID);
                if (inst == null || inst.Members.Any(x => x.UserName == thisInv.Sender) == false)
                {
                    ModelState.AddModelError("Instance", "No Instance found!");
                }
                else
                {
                    if (Accept)
                    {
                        var mem = new Member { InstanceID = inst.InstanceID, UserName = Generic.GetUserName() };
                        db.Members.Add(mem);
                    }
                    thisInv.Reply(Accept);
                    db.SaveChanges();
                }
                return Json(new { refresh = true });
            }
            return Json(new { error = Generic.GetValidationErrors(ModelState) });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RejectInvite(int InviteID)
        {
            var thisInv = db.Invites.Find(InviteID);
            if (thisInv == null || thisInv.Active == false)
            {

Ikaros/Views/Instances/Create.cshtml
@model Genxyz.Models.Instance

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Instance</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Creator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Creator, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Creator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Ikaros/Views/Instances/Delete.cshtml
@model Genxyz.Models.Instance

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Instance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Creator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Creator)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Ikaros/Views/Instances/Details.cshtml
@model Genxyz.Models.Instance

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Instance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Creator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Creator)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.InstanceID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Ikaros/Views/Instances/Edit.cshtml
@model Genxyz.Models.Instance

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Instance</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.InstanceID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Creator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Creator, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Creator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Ikaros/Views/Instances/MassDataCreate.cshtml
@{
    ViewBag.Title = "MassDataCreate";
}

<h2>This will create a huge amount of Data!</h2>
@Html.AntiForgeryToken()
@using (Html.BeginForm())
{
    @Html.Label("Password: ") @Html.TextBox("Password")<br />
    @Html.Label("Count: ")@Html.TextBox("Count")<br />
    @Html.Label("InstanceID: ")@Html.TextBox("InstanceID")<br />

    @GenericHelper.FormSubmitButton("Send","danger")
}

Ikaros/Views/Instances/_Configuration.cshtml
@model Genxyz.Models.InstanceConfiguration

@using (Html.BeginForm("CreateJSON", "Instances", FormMethod.Post, new { @class= "removeEnterSubmit" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.InstanceConfigurationID)

        <div class="form-group">
            @Html.LabelFor(model => model.DisplayName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DisplayName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DisplayName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-4"><span type="button" class="btn btn-success button-submit-form" data-target="/Instances/CreateJSON">Create</span></div>
            <div class="col-md-4"></div>
            <div class="col-md-4"><span type="button" class="btn btn-danger button-cancel">Cancel</span></div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Ikaros/Views/Instances/_Create.cshtml
@model Genxyz.Models.InstanceCreate
<div class="col-md-12">
    @using (Html.BeginForm("CreateJSON", "Instances"))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-4">@GenericHelper.FormSubmitButton("Create", "success")</div>
            <div class="col-md-4"></div>
            <div class="col-md-4">@GenericHelper.Button("Cancel", "", "danger", "button-cancel")</div>
        </div>
    }
</div>

Ikaros/Views/Instances/_CreateInvite.cshtml
@model Genxyz.Models.CreateInvite

<div class="inviteRow row">
    Invite Member:<br />
    @using (Html.BeginForm("SendInvite", "Instances"))
    {
        @Html.HiddenFor(model => model.InstanceID)
        @Html.TextBoxFor(model => model.Recipient, new { @placeholder="Email", @class="input-large" })
        <span class="indexButton submit-form-button" data-target="/Instances/SendInvite">Send</span>
        <span class="errorList align-left"></span>
    }
</div>

Ikaros/Views/Instances/_Delete.cshtml
<div class="col-md-12">
    @using (Html.BeginForm("DeleteJSON", "Instances"))
    {        
        <input type="hidden" name="InstanceID" id="deleteInstanceID" />
            <p>Are you certain you wish to delete <span id="deleteInstanceName"></span>? The instance will be lost.</p>
            <div class="col-md-12">
                <div class="col-md-4"><button class="submit-form-button btn btn-danger"><i class="fa fa-trash"> Confirm</i></button></div>
                <div class="col-md-4"></div>
                <div class="col-md-4">@GenericHelper.Button("Cancel", "", "success", "button-cancel")</div>
            </div>
    }
</div>

Ikaros/Views/Instances/_GetInstances.cshtml
@model IEnumerable<Genxyz.Models.InstanceIndex>


    <div class="col-md-12" id="instanceHeader">
        Instances
    </div>
    @foreach (var item in Model)
    {
        <div class="col-md-12 instanceRow">
            <div class="row">
                <div class="col-md-4">
                    <span class="nameField" data-instance="@item.InstanceID">
                        @Html.RouteLink(item.Name, new { action = "Genxyz", controller = "Instances", InstanceID = item.InstanceID }, new { @class = "instanceLink", @data_instance=@item.InstanceID })
                    </span>
                    <span class="nameField" data-instance="@item.InstanceID" hidden>
                        @Html.EditorFor(model => item.Name, new { htmlAttributes = new { @class = "input-large nameInput", @placeholder = "Instance Name...", @data_instance=@item.InstanceID } })
                    </span>
                    <br /><br />
                    @Html.DisplayFor(modelItem => item.CreatorName)<br />
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </div>
                <div class="col-md-4"></div>
                <div class="col-md-4 indexButtons">
                    <br />
                    <span class="indexButton showMembers" data-instance="@item.InstanceID">Share</span>
                    @{
                        string modify = "";
                        if (Generic.GetUserName() == item.Creator)
                        {
                            modify = "<span class=\"indexButton showConfig\" data-instance=\"" + item.InstanceID +
                                "\" data-name=\"" + item.Name + "\">Edit</span>";
                        }
                    }
                    @Html.Raw(modify)

                    @*invite row here.
                    @Html.Action("CreateInvite", "Instances", new { InstanceID = item.InstanceID })*@
                </div>
            </div>
            <div class="row">
                <div hidden class="col-md-12 configRow subDetails" data-instance="@item.InstanceID">
                    @using (Html.BeginForm("EditInstance", "Instances"))
                    {
                        @Html.Hidden("InstanceID", item.InstanceID)
                        @Html.HiddenFor(model => item.Name, new { @class = "itemName", @data_instance = @item.InstanceID })
                        <button type="button" class="indexButton saveConfig" data-instance="@item.InstanceID">Save Changes</button>
                    }
                </div>
            </div>
            <div class="row">
                <div hidden class="col-md-12 memberRow subDetails" data-instance="@item.InstanceID">
                    @Html.Action("InstanceMembers", "Instances", new { InstanceID = item.InstanceID })
                </div>
            </div>
        </div>
    }

Ikaros/Views/Instances/_GetInstancesOLD.cshtml
@model IEnumerable<Genxyz.Models.InstanceIndex>

<table class="table instanceTable">
    <tr class="bottomBorder">
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatorName)
        </th>
        <th>
            @Html.DisplayNameFor(model=> model.CreationDate)
        </th>
        <th>

        </th>
    </tr>

@foreach (var item in Model) {
    <tr class="instanceDetails" data-instance="@item.InstanceID">
        <td>
            @Html.RouteLink(item.Name, new { action="Genxyz", controller ="Instances", InstanceID = item.InstanceID}, new { @class = "instanceLink" })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatorName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreationDate)
        </td>
        <td class="align-right">
        <span class="btn btn-success showMembers" data-instance="@item.InstanceID"><span class="fa fa-group"></span></span>
        @{ 
            string delete = "";
            string modify = "";
            if (Generic.GetUserName() == item.Creator)
            {
                delete = "<span class=\"btn btn-success button-delete-instance openDialog\" data-dialog=\"DeleteInstanceDialog\" data-instance=\"" + item.InstanceID +
                    "\" data-name=\"" + item.Name + "\"><span class=\"fa fa-trash\"></span></span>";
                modify = "<span class=\"btn btn-success button-submit-form showConfig\" data-instance=\"" + item.InstanceID +
                    "\" data-name=\"" + item.Name + "\"><span class=\"fa fa-cog\"></span></span>";
            }
        }
        @Html.Raw(delete)
        @Html.Raw(modify)
        </td>
    </tr>
    //get member row.
    <tr hidden class="memberRow subHeader" data-instance="@item.InstanceID">
        <td></td>
        <td></td>
        <td class="align-right">
            User
        </td>
        <td class="align-left">
            Status
        </td>
    </tr>
    //row for editing.
    <tr hidden class="configRow subHeader" data-instance="@item.InstanceID">
        @using (Html.BeginForm("EditInstance", "Instances", FormMethod.Post))
        { 
            @Html.Hidden("InstanceID", item.InstanceID)
            <td>@Html.EditorFor(model => item.Name)</td>
            <td></td>
            <td></td>
            <td>
                <button type="button" class="btn btn-success submit-form-button saveConfig" data-instance="@item.InstanceID">Save Changes</button>
            </td>
        }
    </tr>
    @Html.Action("InstanceMembers", "Instances", new { InstanceID = item.InstanceID })
            //invite row here.
    @Html.Action("CreateInvite", "Instances", new { InstanceID = item.InstanceID })
    <tr class="bottomBorder">

    </tr>
}
</table>

Ikaros/Views/Instances/_GetInvites.cshtml
@model IEnumerable<Genxyz.Models.Invite>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Sender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InstanceName)
        </th>
        <th>
           
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Sender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InstanceName)
            </td>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("InviteID", item.InviteID)
                <td>
                    <button type="button" class="btn btn-success button-submit-form" data-target="/Instances/AcceptInvite">Accept</button>
                </td>
                <td>
                    <button type="button" class="btn btn-success button-submit-form" data-target="/Instances/RejectInvite">Reject</button>
                </td>
            }
        </tr>
    }
</table>

Ikaros/Views/Instances/_InboundInvites.cshtml
@model IEnumerable<Genxyz.Models.InboundInvites>

<div class="indexSubHeader"></div>
<table class="table instanceTable">

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.InstanceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sender)
        </th>
        <th>
           @Html.DisplayNameFor(model=> model.DateSent)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.InstanceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateSent)
            </td>
                <td>
                    <span class="replyInvite btn btn-success" data-value="@item.InviteID" data-accept="true"><span class="fa fa-check"></span></span>
                    <span class="replyInvite btn btn-danger" data-value="@item.InviteID" data-accept="false"><span class="fa fa-close"></span></span>
                </td>
        </tr>
    }
</table>

Ikaros/Views/Instances/_InstanceMembers.cshtml
@model IEnumerable<Genxyz.Models.MemberList>

<div class="row" id="memberRow">
    <table>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.UserName</td>
                <td>@item.State</td>
            </tr>
        }
    </table>
</div>
@Html.Action("CreateInvite", "Instances", new { InstanceID = ViewBag.InstanceID })